# Base Stage
FROM node:22-alpine AS base

WORKDIR /app

COPY ./package*.json ./

RUN npm install

# Production Builder Stage
FROM base AS builder

COPY . . 

RUN npm run build

# Production Stage
FROM nginx:stable-alpine AS prod

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]